const mongoose = require('mongoose');

const ticketSchema = new mongoose.Schema({
    ticketNumber: { type: String, required: true, unique: true },
    customerName: { type: String, required: true },
    customerPhone: String,
    customerEmail: String,
    customerAddress: String,
    serviceType: { type: String, required: true },
    description: String,
    priority: { type: String, enum: ['Low', 'Medium', 'High', 'Critical'], default: 'Medium' },
    status: { type: String, enum: ['Open', 'In Progress', 'Resolved', 'Cancelled', 'Closed'], default: 'Open' },
    assignedTo: String,
    createdAt: { type: Date, default: Date.now },
    scheduledDate: Date,
    serviceRequiredDate: Date,
    completionDate: Date,
    engineSerialNumber: String,
    magiecCode: String,
    siteId: String,
    siteLocation: String,
    stateName: String,
    vertical: String,
    invoiceRaised: { type: Boolean, default: false },
    serviceCharge: Number,
    product: String,
    workCompleted: String,
    partsUsed: [{ partName: String, quantity: Number, serialNumber: String }],
    recommendations: String,
    customerFeedback: String,
    serviceQuality: String,
    customerSatisfaction: Number, 
    technicianSignature: String,
    customerSignature: String,
    photos: [String],      
    attachments: [String], 
});

module.exports = mongoose.model('Ticket', ticketSchema);
